# Generated by Django 4.2.3 on 2024-02-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('seller_email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='Products/')),
            ],
        ),
    ]
