# Generated by Django 4.2.3 on 2024-02-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_products_id_alter_products_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seller_email',
            field=models.EmailField(default='rohan@gmail.com', max_length=40),
        ),
    ]
