# Generated by Django 4.2.3 on 2024-02-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_alter_products_seller_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.EmailField(default='rohan@gmail.com', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='Products/')),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
