# Generated by Django 4.2.3 on 2024-03-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_product_details_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
