# Generated by Django 4.2.3 on 2024-03-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_remove_orders_state_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='rohan@gmail.com', max_length=25),
        ),
    ]
