# Generated by Django 4.2.3 on 2024-03-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_orders_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
